version: '2'
services:
  secrets:
    build: .
    image: umputun/secrets:latest
    container_name: secrets
    #hostname: secrets
    restart: always
    # uncomment to expose directly without nginx proxy
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080

