name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test
      run: cd app && go test -v -timeout=60s -covermode=count -coverprofile=$GITHUB_WORKSPACE/profile.cov
    
    - name: install golangci-lint and goveralls
      run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.43.0
          GO111MODULE=off go get -u github.com/mattn/goveralls
        
    - name: build
      run:  go mod vendor && go build -v -mod=vendor
      working-directory: app  
  
    - name: submit coverage
      run: go get -u github.com/mattn/goveralls && cd $(go env GOPATH)/bin && ls -la && cd .. && ls -la && $(go env GOPATH)/bin/goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      working-directory: app
